const min_distance = 10; //10 cm
const max_distance = 150; //150 cm or 1.5 m


function getRandomInt(min, max){
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min;
}


function generateQuestion(){
    const questionType = Math.random() < 0.5 ? 'less' : 'greater';
    const distanceValue = getRandomInt(max_distance, min_distance);

    const text = `Find a Target ${questionType === 'less' ? 'less than' : 'greater than'} ${distanceValue} cm`;

    return {
        text: text,
        type: questionType, 
        value: distanceValue
    };
}


/**
 * Checks if the measured distance from the sensor satisfies the question's condition.
 * @param {object} question The question object generated by generateQuestion().
 * @param {number} measuredDistance The distance measured by the ESP32.
 * @returns {boolean} True if the answer is correct, false otherwise.
 */
function checkAnswer(question, measuredDistance) {
    if (!question || typeof measuredDistance !== 'number') {
        return false;
    }

    if (question.type === 'less') {
        return measuredDistance < question.value && measuredDistance > 0; // Ensure distance is positive
    } else if (question.type === 'greater') {
        return measuredDistance > question.value;
    }
    
    // Default to false if the question type is unknown
    return false;
}

module.exports = {
    generateQuestion,
    checkAnswer
};
